---
- name: Update apt cache
  apt: update_cache=yes
  become: true
  become_method: sudo
  when: package_update

- name: Upgrade apt packages
  apt: upgrade=yes
  become: true
  become_method: sudo
  when: package_upgrade
