language: python
python:
  - "2.7"
sudo: required
dist:
  - "xenial"

# envoronments
env:
  - SITE=test.yml

addons:
  apt:
    packages:
      - python-pip

before_install:
  - sudo apt-get update -qq

# command to install dependencies
install:
  # Install Ansible.
  - pip install ansible

# command to run tests
script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local
