---
- name: Install zsh with Homebrew
  homebrew: name=zsh state=latest

# http://zanshin.net/2013/09/03/how-to-use-homebrew-zsh-instead-of-max-os-x-default/
- name: Add zsh to /etc/shells
  lineinfile:
    line: /usr/local/bin/zsh
    dest: /etc/shells
    state: present
  register: zsh_shells
  become: true
  become_method: sudo

- name: Change default shell to zsh
  command: chsh -s /usr/local/bin/zsh
  # Only run this if above task was changed
  when: zsh_shells.changed
  become: true
