---
- include_tasks: "install-{{ ansible_os_family | lower }}.yml"

- import_tasks: link-shell-configs.yml

- name: Link global gitignore file
  file:
    src: "{{ dotfiles_home }}/roles/git/files/gitignore_global.link"
    dest: "{{ ansible_env.HOME }}/.gitignore_global"
    state: link
    force: yes
    follow: no

- name: Link git commit message template file
  file:
    src: "{{ dotfiles_home }}/roles/git/files/gitcommitmsg.link"
    dest: "{{ ansible_env.HOME }}/.gitcommitmsg"
    state: link
    force: yes
    follow: no

- name: Check if gitconfig exists
  stat: path="{{ ansible_env.HOME }}/.gitconfig"
  register: gitconfig_stat

- name: Back up gitconfig
  command: mv ~/.gitconfig ~/.gitconfig.orig
  args:
    creates: "{{ ansible_env.HOME }}/.gitconfig.orig"
  when: gitconfig_stat.stat.exists
  changed_when: false

- name: Make sure gitconfig is up to date
  template:
    src: "gitconfig.j2"
    dest: "{{ ansible_env.HOME }}/.gitconfig"
  changed_when: not gitconfig_stat.stat.exists
